# Comment about this file
#

services:
  vllm-server:
    image: pyt-2.6.0-1.20.0-rel-ub22-vllm-v0.6.6.post1_gaudi-1.20.0-6af2f67
    container_name: vllm-server
    build:
      context: .
      dockerfile: Dockerfile-1.20.0-rel-ub22-vllm-v0.6.6.post1+Gaudi-1.20.0-6af2f67
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    cap_add:
      - SYS_NICE
    ipc: host
    runtime: habana
    ports:
      - 8000:8000
    volumes:
      - ./hf_cache:/hf_cache
      - .:/workdir
    entrypoint: /workdir/server_cmd.sh
    env_file:
     - docker_envfile.env
     - docker_common.env

  vllm-client:
    image: bash
    container_name: pulsecheck
    volumes:
      - .:/workdir
    entrypoint: /workdir/server_pulsecheck.sh initial vllm-server
      #restart: no
    depends_on:
      - vllm-server
    env_file:
     - docker_envfile.env
     - docker_common.env

